use_frameworks!

target 'PYGradientView_Example' do
  pod 'PYGradientView', :path => '../'

  target 'PYGradientView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
